--- #YAML:1.0
name:                Net-sFlow
version:             0.13
abstract:            decode sFlow datagrams
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Elisa Jasinska <elisa@bigwaveit.org>
